preset: laravel
risky: false
enabled:
  - concat_with_spaces
disabled:
  - concat_without_spaces
  - length_ordered_imports
  - not_operator_with_successor_space
  - trim_array_spaces
finder:
  exclude:
  - node_modules
  - storage
  - vendor
  name: "*.php"
  not-name: "*.blade.php"