FROM caronae/backend:latest

RUN apk --no-cache add supervisor

COPY supervisord.conf /etc/supervisord.conf

WORKDIR /etc/supervisor/conf.d/

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
